### PR TITLE
Final URLS

### PR DESCRIPTION
**Pull request by riordan**
Revises all example URLS to point to search.mapzen.com over SSL

### CODE REVIEW

**Comment by rmglennon** [comment]
I'd like to propose making the standard text for where we tell a user to insert an API key be formatted as `your-api-key`. How does that sound?

**Comment by riordan** [comment]
Very much in favor of this. We discussed this about a week ago, where you (@rmglennon) , @dianashk, and I all agreed on this (as I recall).

**Comment by riordan** [comment]
@rmglennon: thoughts on it being all-caps (e.g. `YOUR-API-KEY`) so it stands out?

**Comment by rmglennon** [comment]
hmm, I kind of like it lowercased. We can chat.

Side note, take a look at the place URL; it has an actual key in it (along with my TO DO notes that can be removed if the bug is fixed).

**Comment by riordan** [comment]
Despite our debate, I've gone ahead and switched them all over to `{YOUR-API-KEY}`, not because I'm being a jerk, but because that'll make it easy to find&replace when we do come to our conclusion.

**Comment by missinglink** [comment]
I can't believe this actually works, ended my rant before it even began...

```
$ curl -v "https://search.mapzen.com/v1/search?api_key={search-EEgHGcM}&text=london"
```

watermelon cat

**Comment by dianashk** [comment]
@missinglink Didn't work in the browser.

**Comment by missinglink** [comment]
agh yea, I think you caught me before edited it, bash seemed to be more forgiving than the browser, try refreshing this PR for my updated comment.

**Comment by riordan** [comment]
On our team call we agreed that the best thing would be standardizing across the company the way we indicate API keys as:

`{$servicename}-XXXXXXX` (7 `X`es)

In this case that would be `search-XXXXXXX`.

Need to discuss w/ @baldur catching these in APIAxle.

**Pull request merged**
