### PR TITLE
Add glossary file

### PR DESCRIPTION
**Pull request by rmglennon**
Here's a start to the glossary of common terms in Mapzen Search. See issue #10

Please review and commit more edits and terms, as needed.

Note: This PR contains only the glossary file, not the other changes in PR #45.

### CODE REVIEW

**Comment by orangejulius** [comment]
Excellent definitions. I look forward to improved formatting. It's a bit hard to skim through these at the moment.

**Comment by riordan** [comment]
Absolutely. :+1:

**Comment by rmglennon** [comment]
Thanks, @orangejulius @riordan. I've reworked the formatting a bit to add sections and made the term bold. I'll merge, but let's continue to improve these and add others that we hear.

**Comment by orangejulius** [comment]
The new formatting is great :)

**Comment by riordan** [comment]
Indeed!

Could be good to set each of the words as section headers though, that way
we can treat each as a linkable anchor so we can link to the definition.


On Fri, Oct 9, 2015 at 4:18 PM, Julian Simioni <notifications@github.com>
wrote:

> The new formatting is great :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/pelias-doc/pull/47#issuecomment-146977161>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Pull request merged**
