### PR TITLE
Add size to list of available parameters for autocomplete

### PR DESCRIPTION
**Pull request by JesseCrocker**

### CODE REVIEW

**Comment by dianashk** [comment]
Hey @JesseCrocker, this is actually currently not supported. The autocomplete endpoint always returns 10 results. This was decided upon during the v1.0 Mapzen Search release to make the autocomplete endpoint *cache-friendly*. We're looking to support more options on autocomplete in the near future, but unfortunately updating the docs here is premature. 

If this is a feature you'd like to see implemented sooner rather than later, please weigh in [here](https://github.com/pelias/pelias/issues/249)

**Comment by JesseCrocker** [comment]
I just tried, and https://search.mapzen.com/v1/autocomplete/ definitely uses the size parameter. Does not supported just mean it shouldn't be used?

**Comment by dianashk** [comment]
So... funny story... :confused: we had designed and implemented the `autocomplete` endpoint to not support this, and all this time were under the collective impression that it doesn't. And then your pull request appeared and I answered without trying it first. Others, @riordan and @orangejulius, were more diligent and actually tried it... and guess what!!?? it worked!! awkward. 

So turns out it works, but it kinda shouldn't. We aren't sure yet if we want to document it as a supported feature, or disable it. Stay tuned.

**Comment by missinglink** [comment]
hey @JesseCrocker, I'm going to have to close this in favour of https://github.com/pelias/api/pull/468 which hard-codes the `?size=10` setting for `/v1/autocomplete`.

that was actually the original intended behaviour for that API and it was only not obeying that limit because of a bug, which the PR above fixes.

so in light of that, I'm going to close this issue, thanks for the heads-up, sorry for the confusion, I know someone reached out to you already and I'm told the fix won't adversely effect your work.

**Comment by missinglink** [comment]
ref: https://github.com/pelias/api/blob/autocomplete_api/test/ciao/autocomplete/size_not_default.coffee#L30

**Pull request closed without merging**
