### PR TITLE
Retext Simplified Documentation

### PR DESCRIPTION
**Pull request by riordan**
Simplifies documentation language based on [retext-mapbox-standard](https://github.com/mapbox/retext-mapbox-standard).

There are still several things that don't pass linter muster, but they're key terms for the product (namely "prioritize").

### CODE REVIEW

**Comment by rmglennon** [comment]
Very cool.

**Comment by riordan** [comment]
@rmglennon so this has your seal of approval?

**Comment by rmglennon** [comment]
@riordan - these are look fine. There was one about authoritative sources, but it still had the same meaning. (and can you show me how to run this on all our repos?)

**Comment by riordan** [comment]
Yeah, I couldn't figure out how to rewrite that one error effectively. :disappointed:

And absolutely.

**Pull request merged**
