### PR TITLE
2.x for heapsize link

### PR DESCRIPTION
**Pull request by easherma**

### CODE REVIEW

**Comment by trescube** [comment]
👍

**Comment by orangejulius** [comment]
LGTM

**Comment by orangejulius** [comment]
hate to do this, but please no one else comment on, merge, or edit this PR. we've been having problems with our approval hook for L G T M and this is going to serve as an example of it breaking

**Comment by orangejulius** [comment]
Eh, never mind, gotta merge docs changes so no one gets confused! :P

**Pull request merged**
