### PR TITLE
Installation tweaks

### LINKED ISSUE #55: Update, combine and improve dev instance docs
We have the start of some documentation on how to install everything Pelias related for development purposes on one's local machine, but it's a bit scattered. Part is in [pelias/pelias](https://github.com/pelias/pelias/blob/master/INSTALL.md), part is in each of the importer docs. It would be awesome to combine it all and brush it up, here in the pelias-doc repo.

### PR DESCRIPTION
**Pull request by orangejulius**
Suggestions from @rmglennon 

Fixes #55

### CODE REVIEW

**Comment by rmglennon** [comment]
I'll take a look at this!

I pushed a commit to fix the code block formatting. It turns out that the ```json must be completely valid json, and \\ comments are not allowed, so it adds red blocks around "invalid" json.

In the other ```json code block, it was missing a closing }, so it was being read as invalid there, too.

**Comment by orangejulius** [comment]
ooh! i knew about the comment issue (it's everyone's biggest gripe with json in particular), but not the missing brace. thanks!

**Comment by rmglennon** [comment]
Thanks @orangejulius for putting this together! I haven't tested that the code or steps actually work ;), but it reads OK.

Couple of other comments (take or leave them, up to you):
- For pure tech docs, I'd normally say to keep it all in second person (you, but not "we" or "our"). I think it's OK here.
- Is it Whosonfirst or Who's on First? Maybe a replace-all for the non-code uses. https://whosonfirst.mapzen.com/
- Add a section for considerations for installing for the purpose of contributing to the Pelias code (which also ties with the discussion on all the repo branches).
- Add a general workflow section at the beginning with numbered steps as an overview to make it clear which steps are required and which are optional. Some of these are background thought considerations, and it seems like the real installation part starts toward the end. Maybe put the installation section first, along with any required parts, and then any considerations and discussions on the data import process later? 
- Group the "choose your branch" with the part on downloading the Pelias repositories.
- Is there a way to run Pelias to pull in data we've already processed for Mapzen Search? Wondering if you can avoid the whole planet build stuff, deduplication, and all that.

**Comment by rmglennon** [comment]
Some thoughts on the intro paragraph:

Pelias is an open-source geocoder....(some intro sentence that mentions Pelias first). Pelias code powers Mapzen Search, which is a convenient web service... In some situations, you may choose to install Pelias on your own infrastructure rather than using the Mapzen Search service. For example, you might do this if you want  import your own data, host it on-premises for security purposes or for increased rate limits, or contribute code to the Pelias open-source project.... (or maybe we not even mention Mapzen Search at all here?)

Follow these steps to install Pelias. Some of these processes may be automated... (are there certain parts that work better automated with the Vagrant files, and if so, maybe link to them again from the individual sections on the page?)

**Comment by orangejulius** [comment]
Okay, I've just pushed some updates here. @rmglennon, as usual, thanks for the really helpful feedback.

I've addressed most of the comments you left, as they were all really good questions. The most important, I think, are rewriting the intro, and adding a table of contents. The intro now makes it clear that if you just want to set up your own Pelias, going to the Vagrant image and using that as a foundation is the best way. This document is for more customization, contributing back, and general education about how pelias works.

The TOC also really feels like it makes things clearer, and I've reordered one of the sections to make it fit in with the TOC better.

We don't have a way currently to use our builds for Mapzen Search, but it's been a hot topic of discussion lately, which we will almost certainly be exploring.  When we do we can mention it where appropriate.

**Comment by rmglennon** [comment]
This is good! The TOC at the top is pretty helpful. Merge when ready.

Thanks for writing this @orangejulius.

**Pull request merged**
